import {BASKETBALL, CAR, DRIVE, DUNK_SHOT, FRUITS, MARIO} from "./ids";
import {
  BASKETBALL as BASKETBALL_ROUTE,
  DUNK_SHOT as DUNK_SHOT_ROUTE,
  CAR as CAR_ROUTE,
  MARIO as MARIO_ROUTE,
  FRUITS as FRUITS_ROUTE,
  DRIVE as DRIVE_ROUTE
} from "../../../shared/constants/src/pages/routes";

export const ROUTES = {
  [BASKETBALL]: BASKETBALL_ROUTE,
  [DUNK_SHOT]: DUNK_SHOT_ROUTE,
  [CAR]: CAR_ROUTE,
  [MARIO]: MARIO_ROUTE,
  [FRUITS]: FRUITS_ROUTE,
  [DRIVE]: DRIVE_ROUTE
};