import {BASKETBALL, DRIVE, DUNK_SHOT, FRUITS, MARIO, MATCH3} from "./ids";
import {
  BASKETBALL as BASKETBALL_ROUTE,
  DUNK_SHOT as DUNK_SHOT_ROUTE,
  MATCH3 as MATCH3_ROUTE,
  MARIO as MARIO_ROUTE,
  FRUITS as FRUITS_ROUTE,
  DRIVE as DRIVE_ROUTE
} from "../../../shared/constants/pages/routes";

export const ROUTES = {
  [BASKETBALL]: BASKETBALL_ROUTE,
  [DUNK_SHOT]: DUNK_SHOT_ROUTE,
  [MATCH3]: MATCH3_ROUTE,
  [MARIO]: MARIO_ROUTE,
  [FRUITS]: FRUITS_ROUTE,
  [DRIVE]: DRIVE_ROUTE
};