const COLLISION_CATEGORIES = {
  BALL: 0x0001,
  ACTIVE: 0x0002,
  INACTIVE: 0x0004,
  NEXT: 0x0008,
  WALL: 0x0010,
  SPIKE: 0x0020,
  PREPARE: 0x0040,
  PROTECTED: 0x0080,
  DAMAGE: 0x0160
};

export const COLLISION_FILTERS = {
  BALL: {
    category: COLLISION_CATEGORIES.BALL,
    mask: COLLISION_CATEGORIES.ACTIVE | COLLISION_CATEGORIES.NEXT | COLLISION_CATEGORIES.WALL | COLLISION_CATEGORIES.SPIKE,
    group: 0
  },
  PREPARE: {
    category: COLLISION_CATEGORIES.PREPARE,
    mask: COLLISION_CATEGORIES.ACTIVE | COLLISION_CATEGORIES.WALL,
    group: 0
  },
  ACTIVE: {
    category: COLLISION_CATEGORIES.ACTIVE,
    mask: COLLISION_CATEGORIES.BALL | COLLISION_CATEGORIES.PREPARE,
    group: 0
  },
  INACTIVE: {
    category: COLLISION_CATEGORIES.INACTIVE,
    mask: 0x0000,
    group: -1
  },
  NEXT: {
    category: COLLISION_CATEGORIES.NEXT,
    mask: COLLISION_CATEGORIES.BALL | COLLISION_CATEGORIES.PROTECTED,
    group: 0
  },
  PROTECTED: {
    category: COLLISION_CATEGORIES.PROTECTED,
    mask: COLLISION_CATEGORIES.NEXT,
    group: 0
  },
  WALL: {
    category: COLLISION_CATEGORIES.WALL,
    mask: COLLISION_CATEGORIES.BALL | COLLISION_CATEGORIES.PREPARE | COLLISION_CATEGORIES.DAMAGE,
    group: 0
  },
  SPIKE: {
    category: COLLISION_CATEGORIES.SPIKE,
    mask: COLLISION_CATEGORIES.BALL,
    group: 0
  },
  DAMAGE: {
    category: COLLISION_CATEGORIES.DAMAGE,
    mask: COLLISION_CATEGORIES.WALL,
    group: 0
  }
};
